version: '3.1'
services:
  app_proxy:
    environment:
      APP_HOST: teamspeak_ui_1
      APP_PORT: 8080
  ui:
    image: joni1802/ts3-manager:v2.2.1@sha256:d69890c323e8715cef0f625036c7c51ec7e7da321438897633fff5df83da1e39
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      JWT_SECRET: $APP_SEED
  server:
    image: ertagh/teamspeak3-server:arm64v8-latest-qemu-predownloaded # Or another suitable ARM64 image
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
      TS3SERVER_LICENSE: accept
      TS3SERVER_SERVERADMIN_PASSWORD: $APP_PASSWORD
      # Optional: Set a specific timezone
      # TIME_ZONE: Europe/Berlin
      # Optional: Set user and group IDs for permissions
      # PUID: 1000
      # PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/var/ts3server
